# Generated by Django 2.1.5 on 2019-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='affiche',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
